# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "haproxy1" do |c|
        c.vm.box = "bskton/web"
        c.vm.provision :shell, path: "provision/haproxy1.sh"
        c.vm.network "private_network", ip: "192.168.35.10"
        c.vm.provider "virtualbox" do |vb|
            vb.name = "express-cluster-haproxy1"
            vb.memory = "512"
        end
    end

    config.vm.define "app1" do |c|
        c.vm.box = "bskton/web"
        c.vm.provision :shell, path: "provision/app1.sh"
        c.vm.network "private_network", ip: "192.168.35.20"
        c.vm.provider "virtualbox" do |vb|
            vb.name = "express-cluster-app1"
            vb.memory = "512"
            vb.cpus = 2
        end
    end

    config.vm.define "app2" do |c|
        c.vm.box = "bskton/web"
        c.vm.provision :shell, path: "provision/app2.sh"
        c.vm.network "private_network", ip: "192.168.35.21"
        c.vm.provider "virtualbox" do |vb|
            vb.name = "express-cluster-app2"
            vb.memory = "512"
            vb.cpus = 2
        end
    end
end